---
- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes

- name: restart alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted
    enabled: yes