---
- name: Copy node_exporter binary
  copy:
    src: roles/node_exporter/files/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: '0755'

- name: Create node_exporter systemd service
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=root
      Group=root
      ExecStart=/usr/local/bin/node_exporter
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target

- name: Start node_exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes