---
- name: Copy etcd_exporter binary
  copy:
    src: roles/etcd_exporter/files/etcd_exporter
    dest: /usr/local/bin/etcd_exporter
    mode: '0755'

- name: Create etcd_exporter systemd service
  copy:
    dest: /etc/systemd/system/etcd_exporter.service
    content: |
      [Unit]
      Description=ETCD Exporter
      After=network.target

      [Service]
      User=root
      Group=root
      ExecStart=/usr/local/bin/etcd_exporter --etcd.endpoint=http://localhost:2379
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target

- name: Start etcd_exporter
  systemd:
    name: etcd_exporter
    state: started
    enabled: yes