- name: Add Prometheus datasource to Grafana
  uri:
    url: "http://176.109.82.213:3000/api/datasources"
    method: POST
    user: admin
    password: admin # поменять
    headers:
      Content-Type: application/json
    body: |
      {
        "name": "Prometheus",
        "type": "prometheus",
        "access": "proxy",
        "url": "http://{{ hostvars[groups['balancers'][0]]['ansible_host'] }}:9090",
        "basicAuth": false
      }
    body_format: json
    status_code: 200,409
